[package]
name = "winwin"
version = "0.0.1"
edition = "2021"

[dependencies.windows]
version = "0.56"
features = [
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
